dataflow:

  demo_cdc_landing:
    customer_details_history:
      type: Reader     

      properties:
        yetl.schema.createIfNotExists: true
        yetl.metadata.timeslice: timeslice_file_date_format
        yetl.metadata.filepathFilename: true

      path_date_format: "%Y%m%d"
      file_date_format: "%Y%m%d"
      format: csv
      path: "landing/demo_cdc/customer_details_history/{{ timeslice_path_date_format }}/customer_details_history_{{ timeslice_file_date_format }}.csv"
      read:
        auto: true
        options:
          mode: PERMISSIVE
          inferSchema: false
          header: true
      exceptions:
          path: "delta_lake/{{ database_name }}/customer_details_history_exceptions"
          database: "{{ database_name }}"
          table: "customer_details_history_exceptions"
      thresholds:
        error:
          exception_count: 0
          exception_percent: 0
          max_rows: null
          min_rows: 0
        warning:
          exception_count: 0
          exception_percent: 0
          max_rows: null
          min_rows: 0



  demo_cdc_raw:
    customer_details_history:
      type: DeltaWriter
      partitioned_by: []

      ddl: "{{ root }}"
      properties:
        yetl.metadata.datasetId: true
        yetl.schema.createIfNotExists: true
        delta.appendOnly: false
        delta.checkpoint.writeStatsAsJson: true
        delta.autoOptimize.autoCompact: true       
        delta.autoOptimize.optimizeWrite: true     
        delta.compatibility.symlinkFormatManifest.enabled: false
        delta.dataSkippingNumIndexedCols: -1
        delta.logRetentionDuration: interval 30 days
        delta.deletedFileRetentionDuration: interval 1 week
        delta.enableChangeDataFeed: true
        delta.minReaderVersion: 1
        delta.minWriterVersion: 2
        delta.randomizeFilePrefixes: false
        delta.randomPrefixLength: 2

      format: delta
      path: delta_lake/demo_cdc_raw/customer_details_history
      write:
        mode: append
        options:
          mergeSchema: true